const Joi = require('joi');
const JoiObjectId = require('../utils/joi-objectid')(Joi);

exports.validateRegister = {
  body: Joi.object({
    firstName                 : Joi.string().required().max(40).trim().label("First name"),
    middleName                : Joi.string().max(40).trim().label("Middle name").allow(""),
    lastName                  : Joi.string().required().max(40).trim().label("Last name"),
    email                     : Joi.string().email().required().trim().lowercase(),
    birthDate                 : Joi.date().iso().label("Birth date"),
    gender                    : Joi.string().required(),
    contactNumber             : Joi.string().length(10).pattern(/^[0-9]+$/).required().label("Contact number"),
    emergencyContactNumber    : Joi.string().length(10).pattern(/^[0-9]+$/).allow(""),
    position                  : Joi.string(),  
    correspondenceAddress     : Joi.string().trim().required().label("Correspondence address"),
    permanentAddress          : Joi.string().trim().allow(""),
    department                : JoiObjectId().required(),
    designation               : JoiObjectId().required(),
    vehicalNumber             : Joi.string().allow(""), 
    status                    : Joi.string(),
    role                      : Joi.string(),
    marriageDate              : Joi.string().allow(""),
    degree                    : Joi.string().allow(""),
    collegeName               : Joi.string().allow(""),
    YearOfPassing             : Joi.string().length(4).pattern(/^[0-9]+$/).allow(""),
    ifscCode                  : Joi.string().allow(""),
    accountHolderName         : Joi.string().allow(""),
    bankName                  : Joi.string().allow(""),
    accountNumber             : Joi.string().min(10).allow(""),
    resignationDate           : Joi.string().allow(""),
    noticePeriod              : Joi.string().allow(""),
    lastDate                  : Joi.string().allow(""),
    officeStartTime           : Joi.string().label("Office start time"),
    officeEndTime             : Joi.string().label("Office end time"),
    totalMinutes              : Joi.string().required().label("Total minutes"),
    lateReasonMinute          : Joi.string().label("Late reason minute"),
    attendanceType            : Joi.string().required(),
    overtime                  : Joi.string(),
    overTimeMinute            : Joi.string().pattern(/^[0-9]+$/).required().label("Over time minute"),
    leaveCreditType           : Joi.string().required(),
    leaveTotalMinutes         : Joi.string().required(),
    organizationType          : Joi.string().required(),
    password                  : Joi.string().required().min(8).max(32).trim(),
    confirmPassword           : Joi.string().required().min(8).max(32).trim().label("Confirm password")
    })
}

exports.validateUpdatedEmployee = {  
  body: Joi.object({  
    firstName                 : Joi.string().required().max(40).trim().label("First name"),
    middleName                : Joi.string().max(40).trim().label("Middle name").allow(""),
    lastName                  : Joi.string().required().max(40).trim().label("Last name"),
    email                     : Joi.string().email().required().trim().lowercase(),
    birthDate                 : Joi.date().iso().label("Birth date"),
    gender                    : Joi.string().required(),
    contactNumber             : Joi.string().length(10).pattern(/^[0-9]+$/).required().label("Contact number"),
    emergencyContactNumber    : Joi.string().length(10).pattern(/^[0-9]+$/).allow(""),
    position                  : Joi.string(),
    correspondenceAddress     : Joi.string().trim().required().label("Correspondence address"),
    permanentAddress          : Joi.string().trim().allow(""),
    department                : JoiObjectId().required(),
    designation               : JoiObjectId().required(),
    vehicalNumber             : Joi.string().allow(""), 
    status                    : Joi.string(),
    role                      : Joi.string(),
    marriageDate              : Joi.string().allow(""),
    degree                    : Joi.string().allow(""),
    collegeName               : Joi.string().allow(""),
    YearOfPassing             : Joi.string().length(4).pattern(/^[0-9]+$/).allow(""),
    ifscCode                  : Joi.string().allow(""),
    accountHolderName         : Joi.string().allow(""),
    bankName                  : Joi.string().allow(""),
    accountNumber             : Joi.string().min(10).allow(""),
    resignationDate           : Joi.string().allow(""),
    noticePeriod              : Joi.string().allow(""),
    lastDate                  : Joi.string().allow(""),
    officeStartTime           : Joi.string().label("Office start time"),
    officeEndTime             : Joi.string().label("Office end time"),
    totalMinutes              : Joi.string().required().label("Total minutes"),
    lateReasonMinute          : Joi.string().label("Late reason minute"),
    attendanceType            : Joi.string().required(),
    overtime                  : Joi.string(),
    overTimeMinute            : Joi.string().pattern(/^[0-9]+$/).required().label("Over time minute"),
    leaveCreditType           : Joi.string().required(),
    leaveTotalMinutes         : Joi.string().required(),
    organizationType          : Joi.string().required(),
    })
}

